_BASE_: "Base-RCNN-DilatedC5.yaml"
#_BASE_: "Base-RCNN-DilatedC5_VOC2012.yaml"
#_BASE_: "Base-RCNN-DilatedC5_VOC0712.yaml"
#_BASE_: "Base-RCNN-DilatedC5_VOC2012_Ins.yaml"
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN_WSL_HUWSOD"
  WEIGHTS: "models/DRN-WSOD/resnet50_ws_model_120_d2.pkl"
  #WEIGHTS: "models/DRN-WSOD/resnet50_wsl_119_iter.pth"
  PIXEL_MEAN: [102.9801, 115.9465, 122.7717]
  LOAD_PROPOSALS: True
  BACKBONE:
    NAME: "build_mrrp_wsl_resnet_backbone"
    FREEZE_AT: 5
  MRRP:
    MRRP_ON: True
    NUM_BRANCH: 3
    BRANCH_DILATIONS: [1, 2, 4]
    TEST_BRANCH_IDX: -1
    MRRP_STAGE: "res5"
  RESNETS:
    DEPTH: 50
    RES5_DILATION: 2
  PROPOSAL_GENERATOR:
    NAME: "RPNWSL"
    MIN_SIZE: 40
  RPN:
    IN_FEATURES: ["res5"]
    PRE_NMS_TOPK_TRAIN: 2048
    PRE_NMS_TOPK_TEST: 2048
    POST_NMS_TOPK_TRAIN: 1024
    POST_NMS_TOPK_TEST: 1024
    NMS_THRESH: 0.7
    BATCH_SIZE_PER_IMAGE: 512
    POSITIVE_FRACTION: 0.5
    BBOX_REG_LOSS_TYPE: "smooth_l1"
    IOU_THRESHOLDS: [0.2, 0.6]
  ANCHOR_GENERATOR:
    SIZES: [[32, 64], [128, 256], [512, 768]]
    ASPECT_RATIOS: [[1.0, 2.0, 0.5]]
  ROI_HEADS:
    NAME: "HUWSODROIHeads"
    IN_FEATURES: ["res5"]
    NUM_CLASSES: 20
    SCORE_THRESH_TEST: 0.00001
    NMS_THRESH_TEST: 0.3
  ROI_BOX_HEAD:
    POOLER_TYPE: "ROILoopPool"
    NUM_CONV: 0
    NUM_FC: 2
    DAN_DIM: [2048, 4096]
    BBOX_REG_LOSS_TYPE: "smooth_l1_weighted"
  CLS_HEAD:
    NAME: "AEHead"
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 960, 992, 1024, 1056, 1088, 1120, 1152, 1184, 1216)
  MAX_SIZE_TRAIN: 2000
  MIN_SIZE_TEST: 688
  MAX_SIZE_TEST: 4000
  CROP:
    ENABLED: True
SOLVER:
  STEPS: (140000,)
  MAX_ITER: 200000  # 160.0 epochs for 07
  REFERENCE_WORLD_SIZE: 4
  WARMUP_ITERS: 200
  IMS_PER_BATCH: 4
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0005
TEST:
  AUG:
    ENABLED: True
    MIN_SIZES: (480, 576, 672, 768, 864, 960, 1056, 1152)
    MAX_SIZE: 4000
    FLIP: True
  EVAL_PERIOD: 20000
WSL:
  ITER_SIZE: 1
  WSDDN:
    MEAN_LOSS: True
  OICR:
    REFINE_NUM: 4
    REFINE_REG: [True, True, True, True]
    REFINE_MIST: True
  AE:
    BURNIN_ITERS: 10000
    BURNIN_TYPE: "weak"
    RANK: 1
    RANK_SUPERVISION: 2
  DATA:
    WEAKSTRONG_ON: True
  EMA:
    ENABLE: True
    DECAY: 0.9996
    DIRECTION: "student2teacher_2wsddn_cls"
  HUWSOD:
    #                      0   1   2   3   4     5  6    7   8   9
    # prev_pred_list: [wsddn br1 br2 br3 br4 wsddn br1 br2 br3 br4]
    #                        br1 br2 br3 br4       br1 br2 br3 br4
    BRANCH_SUPERVISION: [-1, -1, -1, -1, 0, 1, 2, 3]
    RPN_SUPERVISION: [4, 4]
    WEAK_CLS_WEIGHT: 1
    WEAK_REG_WEIGHT: 1
    STRONG_CLS_WEIGHT: 1
    STRONG_REG_WEIGHT: 1
  SAMPLING:
    SAMPLING_ON: True
    IOU_THRESHOLDS: [[0.5], [0.5], [0.5], [0.5]]
    #IOU_THRESHOLDS: [[0.35], [0.4], [0.45], [0.5]]
    IOU_LABELS: [[0, 1], [0, 1], [0, 1], [0, 1]]
    BATCH_SIZE_PER_IMAGE: [4096, 4096, 4096, 4096]
    POSITIVE_FRACTION: [1.0, 1.0, 1.0, 1.0]
VIS_PERIOD: 2560
DATASETS:
  PRECOMPUTED_PROPOSAL_TOPK_TRAIN: 2000
